// Japanese kana data - hiragana, katakana, mnemonics, examples
// Format: { c: char, r: romaji, m: mnemonic, w: example word, wr: word romaji, wm: meaning }
window.JP_DATA = (function() {

  // ========== HIRAGANA — basic 46 ==========
  const hiraganaBasic = [
    { c: 'あ', r: 'a',   w: 'あめ',   wr: 'ame',    wm: 'rain' },
    { c: 'い', r: 'i',   w: 'いぬ',   wr: 'inu',    wm: 'dog' },
    { c: 'う', r: 'u',   w: 'うみ',   wr: 'umi',    wm: 'sea' },
    { c: 'え', r: 'e',   w: 'えき',   wr: 'eki',    wm: 'station' },
    { c: 'お', r: 'o',   w: 'おに',   wr: 'oni',    wm: 'demon' },
    { c: 'か', r: 'ka',  w: 'かさ',   wr: 'kasa',   wm: 'umbrella' },
    { c: 'き', r: 'ki',  w: 'きく',   wr: 'kiku',   wm: 'chrysanthemum' },
    { c: 'く', r: 'ku',  w: 'くも',   wr: 'kumo',   wm: 'cloud / spider' },
    { c: 'け', r: 'ke',  w: 'けむり', wr: 'kemuri', wm: 'smoke' },
    { c: 'こ', r: 'ko',  w: 'こえ',   wr: 'koe',    wm: 'voice' },
    { c: 'さ', r: 'sa',  w: 'さくら', wr: 'sakura', wm: 'cherry blossom' },
    { c: 'し', r: 'shi', w: 'しお',   wr: 'shio',   wm: 'salt' },
    { c: 'す', r: 'su',  w: 'すし',   wr: 'sushi',  wm: 'sushi' },
    { c: 'せ', r: 'se',  w: 'せかい', wr: 'sekai',  wm: 'world' },
    { c: 'そ', r: 'so',  w: 'そら',   wr: 'sora',   wm: 'sky' },
    { c: 'た', r: 'ta',  w: 'たこ',   wr: 'tako',   wm: 'octopus' },
    { c: 'ち', r: 'chi', w: 'ちず',   wr: 'chizu',  wm: 'map' },
    { c: 'つ', r: 'tsu', w: 'つき',   wr: 'tsuki',  wm: 'moon' },
    { c: 'て', r: 'te',  w: 'てがみ', wr: 'tegami', wm: 'letter' },
    { c: 'と', r: 'to',  w: 'とり',   wr: 'tori',   wm: 'bird' },
    { c: 'な', r: 'na',  w: 'なつ',   wr: 'natsu',  wm: 'summer' },
    { c: 'に', r: 'ni',  w: 'にく',   wr: 'niku',   wm: 'meat' },
    { c: 'ぬ', r: 'nu',  w: 'ぬま',   wr: 'numa',   wm: 'swamp' },
    { c: 'ね', r: 'ne',  w: 'ねこ',   wr: 'neko',   wm: 'cat' },
    { c: 'の', r: 'no',  w: 'のり',   wr: 'nori',   wm: 'seaweed' },
    { c: 'は', r: 'ha',  w: 'はな',   wr: 'hana',   wm: 'flower / nose' },
    { c: 'ひ', r: 'hi',  w: 'ひと',   wr: 'hito',   wm: 'person' },
    { c: 'ふ', r: 'fu',  w: 'ふゆ',   wr: 'fuyu',   wm: 'winter' },
    { c: 'へ', r: 'he',  w: 'へや',   wr: 'heya',   wm: 'room' },
    { c: 'ほ', r: 'ho',  w: 'ほし',   wr: 'hoshi',  wm: 'star' },
    { c: 'ま', r: 'ma',  w: 'まど',   wr: 'mado',   wm: 'window' },
    { c: 'み', r: 'mi',  w: 'みず',   wr: 'mizu',   wm: 'water' },
    { c: 'む', r: 'mu',  w: 'むら',   wr: 'mura',   wm: 'village' },
    { c: 'め', r: 'me',  w: 'め',     wr: 'me',     wm: 'eye' },
    { c: 'も', r: 'mo',  w: 'もり',   wr: 'mori',   wm: 'forest' },
    { c: 'や', r: 'ya',  w: 'やま',   wr: 'yama',   wm: 'mountain' },
    { c: 'ゆ', r: 'yu',  w: 'ゆき',   wr: 'yuki',   wm: 'snow' },
    { c: 'よ', r: 'yo',  w: 'よる',   wr: 'yoru',   wm: 'night' },
    { c: 'ら', r: 'ra',  w: 'らく',   wr: 'raku',   wm: 'easy / comfort' },
    { c: 'り', r: 'ri',  w: 'りんご', wr: 'ringo',  wm: 'apple' },
    { c: 'る', r: 'ru',  w: 'るす',   wr: 'rusu',   wm: 'absent' },
    { c: 'れ', r: 're',  w: 'れい',   wr: 'rei',    wm: 'zero / bow' },
    { c: 'ろ', r: 'ro',  w: 'ろく',   wr: 'roku',   wm: 'six' },
    { c: 'わ', r: 'wa',  w: 'わたし', wr: 'watashi',wm: 'I / me' },
    { c: 'を', r: 'wo',  w: 'を',     wr: 'wo',     wm: 'object particle' },
    { c: 'ん', r: 'n',   w: 'ほん',   wr: 'hon',    wm: 'book' },
  ];

  // ========== HIRAGANA — dakuten / handakuten ==========
  const hiraganaDakuten = [
    { c: 'が', r: 'ga', w: 'がっこう',     wr: 'gakkou',  wm: 'school' },
    { c: 'ぎ', r: 'gi', w: 'ぎんこう',     wr: 'ginkou',  wm: 'bank' },
    { c: 'ぐ', r: 'gu', w: 'ぐあい',       wr: 'guai',    wm: 'condition' },
    { c: 'げ', r: 'ge', w: 'げんき',       wr: 'genki',   wm: 'energetic' },
    { c: 'ご', r: 'go', w: 'ごはん',       wr: 'gohan',   wm: 'rice / meal' },
    { c: 'ざ', r: 'za', w: 'ざっし',       wr: 'zasshi',  wm: 'magazine' },
    { c: 'じ', r: 'ji', w: 'じかん',       wr: 'jikan',   wm: 'time' },
    { c: 'ず', r: 'zu', w: 'ずっと',       wr: 'zutto',   wm: 'always' },
    { c: 'ぜ', r: 'ze', w: 'ぜんぶ',       wr: 'zenbu',   wm: 'all' },
    { c: 'ぞ', r: 'zo', w: 'ぞう',         wr: 'zou',     wm: 'elephant' },
    { c: 'だ', r: 'da', w: 'だいがく',     wr: 'daigaku', wm: 'university' },
    { c: 'ぢ', r: 'ji', w: 'はなぢ',       wr: 'hanaji',  wm: 'nosebleed (rare — same sound as じ)' },
    { c: 'づ', r: 'zu', w: 'つづく',       wr: 'tsuzuku', wm: 'continue (rare — same sound as ず)' },
    { c: 'で', r: 'de', w: 'でんわ',       wr: 'denwa',   wm: 'telephone' },
    { c: 'ど', r: 'do', w: 'どこ',         wr: 'doko',    wm: 'where' },
    { c: 'ば', r: 'ba', w: 'ばす',         wr: 'basu',    wm: 'bus' },
    { c: 'び', r: 'bi', w: 'びょういん',   wr: 'byouin',  wm: 'hospital' },
    { c: 'ぶ', r: 'bu', w: 'ぶた',         wr: 'buta',    wm: 'pig' },
    { c: 'べ', r: 'be', w: 'べんとう',     wr: 'bentou',  wm: 'lunch box' },
    { c: 'ぼ', r: 'bo', w: 'ぼく',         wr: 'boku',    wm: 'I (male)' },
    { c: 'ぱ', r: 'pa', w: 'ぱん',         wr: 'pan',     wm: 'bread' },
    { c: 'ぴ', r: 'pi', w: 'ぴかぴか',     wr: 'pikapika',wm: 'shiny' },
    { c: 'ぷ', r: 'pu', w: 'ぷーる',       wr: 'puuru',   wm: 'pool' },
    { c: 'ぺ', r: 'pe', w: 'ぺん',         wr: 'pen',     wm: 'pen' },
    { c: 'ぽ', r: 'po', w: 'ぽけっと',     wr: 'poketto', wm: 'pocket' },
  ];

  // ========== KATAKANA — basic 46 ==========
  const katakanaBasic = [
    { c: 'ア', r: 'a',   w: 'アメリカ',   wr: 'amerika',  wm: 'America' },
    { c: 'イ', r: 'i',   w: 'インク',     wr: 'inku',     wm: 'ink' },
    { c: 'ウ', r: 'u',   w: 'ウクライナ', wr: 'ukuraina', wm: 'Ukraine' },
    { c: 'エ', r: 'e',   w: 'エネルギー', wr: 'enerugi-', wm: 'energy' },
    { c: 'オ', r: 'o',   w: 'オレンジ',   wr: 'orenji',   wm: 'orange' },
    { c: 'カ', r: 'ka',  w: 'カメラ',     wr: 'kamera',   wm: 'camera' },
    { c: 'キ', r: 'ki',  w: 'キロ',       wr: 'kiro',     wm: 'kilo' },
    { c: 'ク', r: 'ku',  w: 'クラス',     wr: 'kurasu',   wm: 'class' },
    { c: 'ケ', r: 'ke',  w: 'ケーキ',     wr: 'ke-ki',    wm: 'cake' },
    { c: 'コ', r: 'ko',  w: 'コーヒー',   wr: 'ko-hi-',   wm: 'coffee' },
    { c: 'サ', r: 'sa',  w: 'サラダ',     wr: 'sarada',   wm: 'salad' },
    { c: 'シ', r: 'shi', w: 'シャツ',     wr: 'shatsu',   wm: 'shirt' },
    { c: 'ス', r: 'su',  w: 'スープ',     wr: 'su-pu',    wm: 'soup' },
    { c: 'セ', r: 'se',  w: 'セーター',   wr: 'se-ta-',   wm: 'sweater' },
    { c: 'ソ', r: 'so',  w: 'ソース',     wr: 'so-su',    wm: 'sauce' },
    { c: 'タ', r: 'ta',  w: 'タクシー',   wr: 'takushi-', wm: 'taxi' },
    { c: 'チ', r: 'chi', w: 'チーズ',     wr: 'chi-zu',   wm: 'cheese' },
    { c: 'ツ', r: 'tsu', w: 'ツアー',     wr: 'tsua-',    wm: 'tour' },
    { c: 'テ', r: 'te',  w: 'テスト',     wr: 'tesuto',   wm: 'test' },
    { c: 'ト', r: 'to',  w: 'トマト',     wr: 'tomato',   wm: 'tomato' },
    { c: 'ナ', r: 'na',  w: 'ナイフ',     wr: 'naifu',    wm: 'knife' },
    { c: 'ニ', r: 'ni',  w: 'ニュース',   wr: 'nyu-su',   wm: 'news' },
    { c: 'ヌ', r: 'nu',  w: 'カヌー',     wr: 'kanu-',    wm: 'canoe' },
    { c: 'ネ', r: 'ne',  w: 'ネクタイ',   wr: 'nekutai',  wm: 'necktie' },
    { c: 'ノ', r: 'no',  w: 'ノート',     wr: 'no-to',    wm: 'notebook' },
    { c: 'ハ', r: 'ha',  w: 'ハム',       wr: 'hamu',     wm: 'ham' },
    { c: 'ヒ', r: 'hi',  w: 'ヒーロー',   wr: 'hi-ro-',   wm: 'hero' },
    { c: 'フ', r: 'fu',  w: 'フランス',   wr: 'furansu',  wm: 'France' },
    { c: 'ヘ', r: 'he',  w: 'ヘリ',       wr: 'heri',     wm: 'helicopter' },
    { c: 'ホ', r: 'ho',  w: 'ホテル',     wr: 'hoteru',   wm: 'hotel' },
    { c: 'マ', r: 'ma',  w: 'マンガ',     wr: 'manga',    wm: 'manga' },
    { c: 'ミ', r: 'mi',  w: 'ミルク',     wr: 'miruku',   wm: 'milk' },
    { c: 'ム', r: 'mu',  w: 'ムード',     wr: 'mu-do',    wm: 'mood' },
    { c: 'メ', r: 'me',  w: 'メール',     wr: 'me-ru',    wm: 'email' },
    { c: 'モ', r: 'mo',  w: 'モデル',     wr: 'moderu',   wm: 'model' },
    { c: 'ヤ', r: 'ya',  w: 'ヤード',     wr: 'ya-do',    wm: 'yard' },
    { c: 'ユ', r: 'yu',  w: 'ユーモア',   wr: 'yu-moa',   wm: 'humor' },
    { c: 'ヨ', r: 'yo',  w: 'ヨーグルト', wr: 'yo-guruto',wm: 'yogurt' },
    { c: 'ラ', r: 'ra',  w: 'ラジオ',     wr: 'rajio',    wm: 'radio' },
    { c: 'リ', r: 'ri',  w: 'リスト',     wr: 'risuto',   wm: 'list' },
    { c: 'ル', r: 'ru',  w: 'ルール',     wr: 'ru-ru',    wm: 'rule' },
    { c: 'レ', r: 're',  w: 'レモン',     wr: 'remon',    wm: 'lemon' },
    { c: 'ロ', r: 'ro',  w: 'ロボット',   wr: 'robotto',  wm: 'robot' },
    { c: 'ワ', r: 'wa',  w: 'ワイン',     wr: 'wain',     wm: 'wine' },
    { c: 'ヲ', r: 'wo',  w: 'ヲ',         wr: 'wo',       wm: 'object particle (rare)' },
    { c: 'ン', r: 'n',   w: 'パン',       wr: 'pan',      wm: 'bread' },
  ];

  // ========== KATAKANA — dakuten / handakuten ==========
  const katakanaDakuten = [
    { c: 'ガ', r: 'ga', w: 'ガス',     wr: 'gasu',    wm: 'gas' },
    { c: 'ギ', r: 'gi', w: 'ギター',   wr: 'gita-',   wm: 'guitar' },
    { c: 'グ', r: 'gu', w: 'グラム',   wr: 'guramu',  wm: 'gram' },
    { c: 'ゲ', r: 'ge', w: 'ゲーム',   wr: 'ge-mu',   wm: 'game' },
    { c: 'ゴ', r: 'go', w: 'ゴルフ',   wr: 'gorufu',  wm: 'golf' },
    { c: 'ザ', r: 'za', w: 'ピザ',     wr: 'piza',    wm: 'pizza' },
    { c: 'ジ', r: 'ji', w: 'ジュース', wr: 'ju-su',   wm: 'juice' },
    { c: 'ズ', r: 'zu', w: 'ズボン',   wr: 'zubon',   wm: 'pants' },
    { c: 'ゼ', r: 'ze', w: 'ゼロ',     wr: 'zero',    wm: 'zero' },
    { c: 'ゾ', r: 'zo', w: 'リゾート', wr: 'rizo-to', wm: 'resort' },
    { c: 'ダ', r: 'da', w: 'ダンス',   wr: 'dansu',   wm: 'dance' },
    { c: 'ヂ', r: 'ji', w: 'ヂ',       wr: 'ji',      wm: 'rare ji (same sound as ジ)' },
    { c: 'ヅ', r: 'zu', w: 'ヅ',       wr: 'zu',      wm: 'rare zu (same sound as ズ)' },
    { c: 'デ', r: 'de', w: 'デート',   wr: 'de-to',   wm: 'date' },
    { c: 'ド', r: 'do', w: 'ドア',     wr: 'doa',     wm: 'door' },
    { c: 'バ', r: 'ba', w: 'バナナ',   wr: 'banana',  wm: 'banana' },
    { c: 'ビ', r: 'bi', w: 'ビール',   wr: 'bi-ru',   wm: 'beer' },
    { c: 'ブ', r: 'bu', w: 'ブラシ',   wr: 'burashi', wm: 'brush' },
    { c: 'ベ', r: 'be', w: 'ベッド',   wr: 'beddo',   wm: 'bed' },
    { c: 'ボ', r: 'bo', w: 'ボタン',   wr: 'botan',   wm: 'button' },
    { c: 'パ', r: 'pa', w: 'パスタ',   wr: 'pasuta',  wm: 'pasta' },
    { c: 'ピ', r: 'pi', w: 'ピアノ',   wr: 'piano',   wm: 'piano' },
    { c: 'プ', r: 'pu', w: 'プリン',   wr: 'purin',   wm: 'pudding' },
    { c: 'ペ', r: 'pe', w: 'ペット',   wr: 'petto',   wm: 'pet' },
    { c: 'ポ', r: 'po', w: 'ポスト',   wr: 'posuto',  wm: 'mailbox' },
  ];

  // ========== Fun facts about Japanese ==========
  const facts = [
    'Japanese has three writing systems: hiragana ひらがな (curvy native), katakana カタカナ (angular for foreign words), and kanji 漢字 (Chinese characters).',
    'Hiragana evolved from cursive Chinese characters around the 9th century. It was originally called "women\'s writing" (女手 onnade).',
    'Katakana was developed by Buddhist monks who used fragments of kanji as shorthand notes — that\'s why it looks angular.',
    'There are 46 basic kana in each script — learn them and you can read every sound in Japanese.',
    'Japanese has only 5 vowels: あ い う え お (a, i, u, e, o). Every kana ends in one of these (except ん).',
    'The kana ん/ン is the only one that doesn\'t need a vowel — it\'s a single consonant "n" sound.',
    'を/ヲ is almost only used as the object particle "wo" (pronounced "o") in modern Japanese.',
    'Japanese is written top-to-bottom, right-to-left traditionally — but left-to-right is now common too.',
    'A small つ (っ) doubles the next consonant — がっこう (gakkou, school) has a pause before the "k".',
    'Loan words like コーヒー (coffee), パン (bread, from Portuguese), and アルバイト (part-time job, from German) all use katakana.',
    'The same word can be written in hiragana, katakana, or kanji — each gives a different feel. すし vs スシ vs 寿司.',
    'Japanese has no spaces between words. Native speakers parse them by recognizing kanji and grammatical particles.',
    'There are about 2,136 "everyday-use" kanji (常用漢字 jōyō kanji) taught through high school.',
    'Counting in Japanese uses different "counter words" depending on the shape — 一本 (one long thing), 一枚 (one flat thing), 一個 (one general thing).',
    'Tofugu, Wanikani, and Anki are the most popular tools for learning Japanese — but flashcards like these work too!',
    'Pronunciation tip: every syllable gets equal stress and timing. "Tokyo" is to-u-kyo-u, four equal beats.',
    'Manga (漫画) means "whimsical drawings" and dates back to 12th-century scrolls of frolicking animals.',
    'The word "emoji" 絵文字 literally means "picture character" — え (picture) + も じ (character).',
    'Japanese borrowed thousands of words from English: テレビ (TV), コンピューター (computer), アイスクリーム (ice cream).',
    'The longest Japanese word is 竜宮の乙姫の元結の切り外し — a 22-character name for a type of seaweed.',
  ];

  // ========== Quotes / encouragement ==========
  const quotes = [
    { jp: '千里の道も一歩から', romaji: 'Senri no michi mo ippo kara', en: 'Every journey of a thousand miles begins with a single step' },
    { jp: '七転び八起き',          romaji: 'Nanakorobi yaoki',          en: 'Fall seven times, stand up eight' },
    { jp: '塵も積もれば山となる',  romaji: 'Chiri mo tsumoreba yama to naru', en: 'Even dust amassed will become a mountain' },
    { jp: '猿も木から落ちる',      romaji: 'Saru mo ki kara ochiru',     en: 'Even monkeys fall from trees — everyone makes mistakes' },
    { jp: '一期一会',               romaji: 'Ichigo ichie',               en: 'One time, one meeting — treasure every encounter' },
    { jp: '頑張って！',             romaji: 'Ganbatte!',                  en: 'Do your best! Hang in there!' },
    { jp: '日進月歩',               romaji: 'Nisshin geppo',              en: 'Daily progress, monthly advance' },
    { jp: '初心忘るべからず',      romaji: 'Shoshin wasuru bekarazu',    en: 'Never forget your beginner\'s spirit' },
  ];

  // ========== Vocabulary — 100 essential words ==========
  // { w: kana, r: romaji, m: meaning, cat: category, k?: kanji form }
  const words = [
    // Greetings (10)
    { w: 'こんにちは', r: 'konnichiwa', m: 'hello / good afternoon', cat: 'greet', k: '今日は' },
    { w: 'おはよう',   r: 'ohayou',     m: 'good morning',           cat: 'greet' },
    { w: 'こんばんは', r: 'konbanwa',   m: 'good evening',           cat: 'greet', k: '今晩は' },
    { w: 'さようなら', r: 'sayounara',  m: 'goodbye',                cat: 'greet' },
    { w: 'ありがとう', r: 'arigatou',   m: 'thank you',              cat: 'greet', k: '有難う' },
    { w: 'すみません', r: 'sumimasen',  m: 'excuse me / sorry',      cat: 'greet' },
    { w: 'はい',       r: 'hai',        m: 'yes',                    cat: 'greet' },
    { w: 'いいえ',     r: 'iie',        m: 'no',                     cat: 'greet' },
    { w: 'おやすみ',   r: 'oyasumi',    m: 'good night',             cat: 'greet' },
    { w: 'いただきます', r: 'itadakimasu', m: '"I humbly receive" — said before eating', cat: 'greet', k: '頂きます' },

    // Numbers (10)
    { w: 'いち', r: 'ichi',  m: 'one',   cat: 'num', k: '一' },
    { w: 'に',   r: 'ni',    m: 'two',   cat: 'num', k: '二' },
    { w: 'さん', r: 'san',   m: 'three', cat: 'num', k: '三' },
    { w: 'よん', r: 'yon',   m: 'four',  cat: 'num', k: '四' },
    { w: 'ご',   r: 'go',    m: 'five',  cat: 'num', k: '五' },
    { w: 'ろく', r: 'roku',  m: 'six',   cat: 'num', k: '六' },
    { w: 'なな', r: 'nana',  m: 'seven', cat: 'num', k: '七' },
    { w: 'はち', r: 'hachi', m: 'eight', cat: 'num', k: '八' },
    { w: 'きゅう', r: 'kyuu', m: 'nine', cat: 'num', k: '九' },
    { w: 'じゅう', r: 'juu',  m: 'ten',  cat: 'num', k: '十' },

    // People / Pronouns (8)
    { w: 'わたし',     r: 'watashi',   m: 'I / me',     cat: 'people', k: '私' },
    { w: 'あなた',     r: 'anata',     m: 'you',        cat: 'people' },
    { w: 'かれ',       r: 'kare',      m: 'he',         cat: 'people', k: '彼' },
    { w: 'かのじょ',   r: 'kanojo',    m: 'she',        cat: 'people', k: '彼女' },
    { w: 'ともだち',   r: 'tomodachi', m: 'friend',     cat: 'people', k: '友達' },
    { w: 'せんせい',   r: 'sensei',    m: 'teacher',    cat: 'people', k: '先生' },
    { w: 'がくせい',   r: 'gakusei',   m: 'student',    cat: 'people', k: '学生' },
    { w: 'ひと',       r: 'hito',      m: 'person',     cat: 'people', k: '人' },

    // Family (8)
    { w: 'かぞく',     r: 'kazoku',   m: 'family',          cat: 'family', k: '家族' },
    { w: 'おかあさん', r: 'okaasan',  m: 'mother',          cat: 'family', k: 'お母さん' },
    { w: 'おとうさん', r: 'otousan',  m: 'father',          cat: 'family', k: 'お父さん' },
    { w: 'おにいさん', r: 'oniisan',  m: 'older brother',   cat: 'family', k: 'お兄さん' },
    { w: 'おねえさん', r: 'oneesan',  m: 'older sister',    cat: 'family', k: 'お姉さん' },
    { w: 'いもうと',   r: 'imouto',   m: 'younger sister',  cat: 'family', k: '妹' },
    { w: 'おとうと',   r: 'otouto',   m: 'younger brother', cat: 'family', k: '弟' },
    { w: 'こども',     r: 'kodomo',   m: 'child',           cat: 'family', k: '子供' },

    // Time (10)
    { w: 'きょう',     r: 'kyou',     m: 'today',     cat: 'time', k: '今日' },
    { w: 'あした',     r: 'ashita',   m: 'tomorrow',  cat: 'time', k: '明日' },
    { w: 'きのう',     r: 'kinou',    m: 'yesterday', cat: 'time', k: '昨日' },
    { w: 'いま',       r: 'ima',      m: 'now',       cat: 'time', k: '今' },
    { w: 'あさ',       r: 'asa',      m: 'morning',   cat: 'time', k: '朝' },
    { w: 'ひる',       r: 'hiru',     m: 'noon / daytime', cat: 'time', k: '昼' },
    { w: 'よる',       r: 'yoru',     m: 'night',     cat: 'time', k: '夜' },
    { w: 'じかん',     r: 'jikan',    m: 'time / hour', cat: 'time', k: '時間' },
    { w: 'とき',       r: 'toki',     m: 'time / when', cat: 'time', k: '時' },
    { w: 'まいにち',   r: 'mainichi', m: 'every day', cat: 'time', k: '毎日' },

    // Food (12)
    { w: 'ごはん',     r: 'gohan',    m: 'rice / meal',     cat: 'food', k: 'ご飯' },
    { w: 'みず',       r: 'mizu',     m: 'water',           cat: 'food', k: '水' },
    { w: 'おちゃ',     r: 'ocha',     m: 'tea',             cat: 'food', k: 'お茶' },
    { w: 'コーヒー',   r: 'koohii',   m: 'coffee',          cat: 'food' },
    { w: 'パン',       r: 'pan',      m: 'bread',           cat: 'food' },
    { w: 'たまご',     r: 'tamago',   m: 'egg',             cat: 'food', k: '卵' },
    { w: 'にく',       r: 'niku',     m: 'meat',            cat: 'food', k: '肉' },
    { w: 'さかな',     r: 'sakana',   m: 'fish',            cat: 'food', k: '魚' },
    { w: 'やさい',     r: 'yasai',    m: 'vegetable',       cat: 'food', k: '野菜' },
    { w: 'りんご',     r: 'ringo',    m: 'apple',           cat: 'food' },
    { w: 'すし',       r: 'sushi',    m: 'sushi',           cat: 'food', k: '寿司' },
    { w: 'おいしい',   r: 'oishii',   m: 'delicious',       cat: 'food', k: '美味しい' },

    // Body (8)
    { w: 'あたま',     r: 'atama',    m: 'head',            cat: 'body', k: '頭' },
    { w: 'め',         r: 'me',       m: 'eye',             cat: 'body', k: '目' },
    { w: 'みみ',       r: 'mimi',     m: 'ear',             cat: 'body', k: '耳' },
    { w: 'はな',       r: 'hana',     m: 'nose / flower',   cat: 'body', k: '鼻' },
    { w: 'くち',       r: 'kuchi',    m: 'mouth',           cat: 'body', k: '口' },
    { w: 'て',         r: 'te',       m: 'hand',            cat: 'body', k: '手' },
    { w: 'あし',       r: 'ashi',     m: 'leg / foot',      cat: 'body', k: '足' },
    { w: 'こころ',     r: 'kokoro',   m: 'heart / mind',    cat: 'body', k: '心' },

    // Things (10)
    { w: 'ほん',       r: 'hon',      m: 'book',            cat: 'thing', k: '本' },
    { w: 'いえ',       r: 'ie',       m: 'house',           cat: 'thing', k: '家' },
    { w: 'がっこう',   r: 'gakkou',   m: 'school',          cat: 'thing', k: '学校' },
    { w: 'でんしゃ',   r: 'densha',   m: 'train',           cat: 'thing', k: '電車' },
    { w: 'くるま',     r: 'kuruma',   m: 'car',             cat: 'thing', k: '車' },
    { w: 'でんわ',     r: 'denwa',    m: 'telephone',       cat: 'thing', k: '電話' },
    { w: 'かばん',     r: 'kaban',    m: 'bag',             cat: 'thing', k: '鞄' },
    { w: 'かさ',       r: 'kasa',     m: 'umbrella',        cat: 'thing', k: '傘' },
    { w: 'おかね',     r: 'okane',    m: 'money',           cat: 'thing', k: 'お金' },
    { w: 'とけい',     r: 'tokei',    m: 'clock / watch',   cat: 'thing', k: '時計' },

    // Nature / Weather (8)
    { w: 'そら',       r: 'sora',     m: 'sky',             cat: 'nature', k: '空' },
    { w: 'うみ',       r: 'umi',      m: 'sea',             cat: 'nature', k: '海' },
    { w: 'やま',       r: 'yama',     m: 'mountain',        cat: 'nature', k: '山' },
    { w: 'かわ',       r: 'kawa',     m: 'river',           cat: 'nature', k: '川' },
    { w: 'あめ',       r: 'ame',      m: 'rain',            cat: 'nature', k: '雨' },
    { w: 'ゆき',       r: 'yuki',     m: 'snow',            cat: 'nature', k: '雪' },
    { w: 'ひ',         r: 'hi',       m: 'sun / day',       cat: 'nature', k: '日' },
    { w: 'つき',       r: 'tsuki',    m: 'moon',            cat: 'nature', k: '月' },

    // Colors (6)
    { w: 'あか',       r: 'aka',      m: 'red',             cat: 'color', k: '赤' },
    { w: 'あお',       r: 'ao',       m: 'blue',            cat: 'color', k: '青' },
    { w: 'しろ',       r: 'shiro',    m: 'white',           cat: 'color', k: '白' },
    { w: 'くろ',       r: 'kuro',     m: 'black',           cat: 'color', k: '黒' },
    { w: 'きいろ',     r: 'kiiro',    m: 'yellow',          cat: 'color', k: '黄色' },
    { w: 'みどり',     r: 'midori',   m: 'green',           cat: 'color', k: '緑' },

    // Verbs (10)
    { w: 'いく',       r: 'iku',      m: 'to go',           cat: 'verb', k: '行く' },
    { w: 'くる',       r: 'kuru',     m: 'to come',         cat: 'verb', k: '来る' },
    { w: 'する',       r: 'suru',     m: 'to do',           cat: 'verb' },
    { w: 'たべる',     r: 'taberu',   m: 'to eat',          cat: 'verb', k: '食べる' },
    { w: 'のむ',       r: 'nomu',     m: 'to drink',        cat: 'verb', k: '飲む' },
    { w: 'みる',       r: 'miru',     m: 'to see / watch',  cat: 'verb', k: '見る' },
    { w: 'きく',       r: 'kiku',     m: 'to listen / ask', cat: 'verb', k: '聞く' },
    { w: 'はなす',     r: 'hanasu',   m: 'to speak',        cat: 'verb', k: '話す' },
    { w: 'よむ',       r: 'yomu',     m: 'to read',         cat: 'verb', k: '読む' },
    { w: 'かく',       r: 'kaku',     m: 'to write',        cat: 'verb', k: '書く' },

    // ===== Expansion pack — Greetings (5) =====
    { w: 'おねがいします', r: 'onegaishimasu', m: 'please / I request',         cat: 'greet', k: 'お願いします' },
    { w: 'どうぞ',         r: 'douzo',         m: 'please / go ahead (offering)', cat: 'greet' },
    { w: 'どうも',         r: 'doumo',         m: 'thanks / hi (casual)',       cat: 'greet' },
    { w: 'がんばって',     r: 'ganbatte',      m: 'good luck / do your best',   cat: 'greet', k: '頑張って' },
    { w: 'だいじょうぶ',   r: 'daijoubu',      m: 'okay / fine / no problem',   cat: 'greet', k: '大丈夫' },

    // ===== Numbers extension (10) =====
    { w: 'ぜろ',     r: 'zero',     m: 'zero',                cat: 'num', k: '零' },
    { w: 'ひゃく',   r: 'hyaku',    m: 'hundred',             cat: 'num', k: '百' },
    { w: 'せん',     r: 'sen',      m: 'thousand',            cat: 'num', k: '千' },
    { w: 'まん',     r: 'man',      m: 'ten thousand',        cat: 'num', k: '万' },
    { w: 'ひとつ',   r: 'hitotsu',  m: 'one (item)',          cat: 'num', k: '一つ' },
    { w: 'ふたつ',   r: 'futatsu',  m: 'two (items)',         cat: 'num', k: '二つ' },
    { w: 'みっつ',   r: 'mittsu',   m: 'three (items)',       cat: 'num', k: '三つ' },
    { w: 'いちばん', r: 'ichiban',  m: 'first / number one / best', cat: 'num', k: '一番' },
    { w: 'ぜんぶ',   r: 'zenbu',    m: 'all / everything',    cat: 'num', k: '全部' },
    { w: 'ちょっと', r: 'chotto',   m: 'a little / a moment', cat: 'num' },

    // ===== People (4 more) =====
    { w: 'おとこ',     r: 'otoko',     m: 'man',     cat: 'people', k: '男' },
    { w: 'おんな',     r: 'onna',      m: 'woman',   cat: 'people', k: '女' },
    { w: 'あかちゃん', r: 'akachan',   m: 'baby',    cat: 'people', k: '赤ちゃん' },
    { w: 'おとな',     r: 'otona',     m: 'adult',   cat: 'people', k: '大人' },

    // ===== Family (2 more) =====
    { w: 'おじいさん', r: 'ojiisan',   m: 'grandfather', cat: 'family', k: 'お祖父さん' },
    { w: 'おばあさん', r: 'obaasan',   m: 'grandmother', cat: 'family', k: 'お祖母さん' },

    // ===== Time (10 more) =====
    { w: 'ごぜん',       r: 'gozen',       m: 'AM / morning',     cat: 'time', k: '午前' },
    { w: 'ごご',         r: 'gogo',        m: 'PM / afternoon',   cat: 'time', k: '午後' },
    { w: 'せんしゅう',   r: 'senshuu',     m: 'last week',        cat: 'time', k: '先週' },
    { w: 'らいしゅう',   r: 'raishuu',     m: 'next week',        cat: 'time', k: '来週' },
    { w: 'きょねん',     r: 'kyonen',      m: 'last year',        cat: 'time', k: '去年' },
    { w: 'らいねん',     r: 'rainen',      m: 'next year',        cat: 'time', k: '来年' },
    { w: 'なんじ',       r: 'nanji',       m: 'what time?',       cat: 'time', k: '何時' },
    { w: 'げつようび',   r: 'getsuyoubi',  m: 'Monday',           cat: 'time', k: '月曜日' },
    { w: 'どようび',     r: 'doyoubi',     m: 'Saturday',         cat: 'time', k: '土曜日' },
    { w: 'にちようび',   r: 'nichiyoubi',  m: 'Sunday',           cat: 'time', k: '日曜日' },

    // ===== Food (10 more) =====
    { w: 'ぎゅうにゅう',   r: 'gyuunyuu',     m: 'milk',          cat: 'food', k: '牛乳' },
    { w: 'ジュース',       r: 'juusu',        m: 'juice',         cat: 'food' },
    { w: 'アイスクリーム', r: 'aisukurimu',   m: 'ice cream',     cat: 'food' },
    { w: 'ケーキ',         r: 'keeki',        m: 'cake',          cat: 'food' },
    { w: 'チョコレート',   r: 'chokoreeto',   m: 'chocolate',     cat: 'food' },
    { w: 'カレー',         r: 'karee',        m: 'curry',         cat: 'food' },
    { w: 'ラーメン',       r: 'raamen',       m: 'ramen',         cat: 'food' },
    { w: 'うどん',         r: 'udon',         m: 'udon noodles',  cat: 'food' },
    { w: 'そば',           r: 'soba',         m: 'soba noodles',  cat: 'food' },
    { w: 'おかし',         r: 'okashi',       m: 'sweets / snacks', cat: 'food', k: 'お菓子' },

    // ===== Body (4 more) =====
    { w: 'かみ', r: 'kami', m: 'hair',           cat: 'body', k: '髪' },
    { w: 'かお', r: 'kao',  m: 'face',           cat: 'body', k: '顔' },
    { w: 'ゆび', r: 'yubi', m: 'finger',         cat: 'body', k: '指' },
    { w: 'ほね', r: 'hone', m: 'bone',           cat: 'body', k: '骨' },

    // ===== Things (10 more) =====
    { w: 'へや',       r: 'heya',     m: 'room',        cat: 'thing', k: '部屋' },
    { w: 'まど',       r: 'mado',     m: 'window',      cat: 'thing', k: '窓' },
    { w: 'ドア',       r: 'doa',      m: 'door',        cat: 'thing' },
    { w: 'いす',       r: 'isu',      m: 'chair',       cat: 'thing', k: '椅子' },
    { w: 'つくえ',     r: 'tsukue',   m: 'desk',        cat: 'thing', k: '机' },
    { w: 'ベッド',     r: 'beddo',    m: 'bed',         cat: 'thing' },
    { w: 'テレビ',     r: 'terebi',   m: 'television',  cat: 'thing' },
    { w: 'パソコン',   r: 'pasokon',  m: 'computer',    cat: 'thing' },
    { w: 'けいたい',   r: 'keitai',   m: 'cell phone',  cat: 'thing', k: '携帯' },
    { w: 'かぎ',       r: 'kagi',     m: 'key',         cat: 'thing', k: '鍵' },

    // ===== Nature (5 more) =====
    { w: 'き',         r: 'ki',       m: 'tree',           cat: 'nature', k: '木' },
    { w: 'いし',       r: 'ishi',     m: 'stone / rock',   cat: 'nature', k: '石' },
    { w: 'ほし',       r: 'hoshi',    m: 'star',           cat: 'nature', k: '星' },
    { w: 'うちゅう',   r: 'uchuu',    m: 'universe / space', cat: 'nature', k: '宇宙' },
    { w: 'もり',       r: 'mori',     m: 'forest',         cat: 'nature', k: '森' },

    // ===== Colors (4 more) =====
    { w: 'ちゃいろ',   r: 'chairo',   m: 'brown',          cat: 'color', k: '茶色' },
    { w: 'むらさき',   r: 'murasaki', m: 'purple',         cat: 'color', k: '紫' },
    { w: 'オレンジ',   r: 'orenji',   m: 'orange',         cat: 'color' },
    { w: 'ピンク',     r: 'pinku',    m: 'pink',           cat: 'color' },

    // ===== Verbs (10 more) =====
    { w: 'ある',       r: 'aru',      m: 'to exist / be (inanimate)', cat: 'verb', k: '有る' },
    { w: 'いる',       r: 'iru',      m: 'to exist / be (animate)',   cat: 'verb', k: '居る' },
    { w: 'かう',       r: 'kau',      m: 'to buy',         cat: 'verb', k: '買う' },
    { w: 'うる',       r: 'uru',      m: 'to sell',        cat: 'verb', k: '売る' },
    { w: 'あう',       r: 'au',       m: 'to meet',        cat: 'verb', k: '会う' },
    { w: 'まつ',       r: 'matsu',    m: 'to wait',        cat: 'verb', k: '待つ' },
    { w: 'たつ',       r: 'tatsu',    m: 'to stand',       cat: 'verb', k: '立つ' },
    { w: 'すわる',     r: 'suwaru',   m: 'to sit',         cat: 'verb', k: '座る' },
    { w: 'ねる',       r: 'neru',     m: 'to sleep',       cat: 'verb', k: '寝る' },
    { w: 'おきる',     r: 'okiru',    m: 'to wake up',     cat: 'verb', k: '起きる' },

    // ===== Places (NEW, 8) =====
    { w: 'えき',       r: 'eki',         m: 'station',          cat: 'place', k: '駅' },
    { w: 'みせ',       r: 'mise',        m: 'shop / store',     cat: 'place', k: '店' },
    { w: 'としょかん', r: 'toshokan',    m: 'library',          cat: 'place', k: '図書館' },
    { w: 'びょういん', r: 'byouin',      m: 'hospital',         cat: 'place', k: '病院' },
    { w: 'こうえん',   r: 'kouen',       m: 'park',             cat: 'place', k: '公園' },
    { w: 'ぎんこう',   r: 'ginkou',      m: 'bank',             cat: 'place', k: '銀行' },
    { w: 'レストラン', r: 'resutoran',   m: 'restaurant',       cat: 'place' },
    { w: 'ホテル',     r: 'hoteru',      m: 'hotel',            cat: 'place' },

    // ===== Adjectives (NEW, 12) =====
    { w: 'おおきい',     r: 'ookii',     m: 'big / large',      cat: 'adj', k: '大きい' },
    { w: 'ちいさい',     r: 'chiisai',   m: 'small',            cat: 'adj', k: '小さい' },
    { w: 'たかい',       r: 'takai',     m: 'tall / expensive', cat: 'adj', k: '高い' },
    { w: 'やすい',       r: 'yasui',     m: 'cheap / easy',     cat: 'adj', k: '安い' },
    { w: 'ながい',       r: 'nagai',     m: 'long',             cat: 'adj', k: '長い' },
    { w: 'みじかい',     r: 'mijikai',   m: 'short',            cat: 'adj', k: '短い' },
    { w: 'あつい',       r: 'atsui',     m: 'hot (weather)',    cat: 'adj', k: '暑い' },
    { w: 'さむい',       r: 'samui',     m: 'cold (weather)',   cat: 'adj', k: '寒い' },
    { w: 'たのしい',     r: 'tanoshii',  m: 'fun / enjoyable',  cat: 'adj', k: '楽しい' },
    { w: 'きれい',       r: 'kirei',     m: 'pretty / clean',   cat: 'adj', k: '綺麗' },
    { w: 'いそがしい',   r: 'isogashii', m: 'busy',             cat: 'adj', k: '忙しい' },
    { w: 'やさしい',     r: 'yasashii',  m: 'kind / easy',      cat: 'adj', k: '優しい' },

    // ===== Animals (NEW, 8) =====
    { w: 'いぬ',     r: 'inu_a',    m: 'dog',     cat: 'animal', k: '犬' },
    { w: 'ねこ',     r: 'neko_a',   m: 'cat',     cat: 'animal', k: '猫' },
    { w: 'とり',     r: 'tori_a',   m: 'bird',    cat: 'animal', k: '鳥' },
    { w: 'うま',     r: 'uma',      m: 'horse',   cat: 'animal', k: '馬' },
    { w: 'うし',     r: 'ushi',     m: 'cow',     cat: 'animal', k: '牛' },
    { w: 'ぶた',     r: 'buta_a',   m: 'pig',     cat: 'animal', k: '豚' },
    { w: 'さる',     r: 'saru',     m: 'monkey',  cat: 'animal', k: '猿' },
    { w: 'きつね',   r: 'kitsune',  m: 'fox',     cat: 'animal', k: '狐' },
  ];

  const wordCategories = [
    { id: 'all',    label: 'All',        icon: 'sparkle' },
    { id: 'greet',  label: 'Greetings',  icon: 'hand' },
    { id: 'num',    label: 'Numbers',    icon: 'hash' },
    { id: 'people', label: 'People',     icon: 'user' },
    { id: 'family', label: 'Family',     icon: 'users' },
    { id: 'time',   label: 'Time',       icon: 'clock' },
    { id: 'food',   label: 'Food',       icon: 'utensils' },
    { id: 'body',   label: 'Body',       icon: 'body' },
    { id: 'thing',  label: 'Things',     icon: 'box' },
    { id: 'place',  label: 'Places',     icon: 'pin' },
    { id: 'nature', label: 'Nature',     icon: 'mountain' },
    { id: 'color',  label: 'Colors',     icon: 'palette' },
    { id: 'animal', label: 'Animals',    icon: 'paw' },
    { id: 'adj',    label: 'Adjectives', icon: 'sparkles' },
    { id: 'verb',   label: 'Verbs',      icon: 'play' },
  ];

  // ========== Easily confused kana ==========
  // Groups of look-alike kana with a tip on how to tell them apart.
  const tricky = [
    { script: 'kata', kana: [{ c: 'シ', r: 'shi' }, { c: 'ツ', r: 'tsu' }],
      hint: 'シ (shi) — strokes are HORIZONTAL, written bottom-up like a smile. ツ (tsu) — strokes are VERTICAL, written top-down like falling rain.' },
    { script: 'kata', kana: [{ c: 'ン', r: 'n' }, { c: 'ソ', r: 'so' }],
      hint: 'ン (n) — long stroke goes UP-and-right (like シ). ソ (so) — long stroke goes DOWN-and-left (like ツ). Same rule as shi/tsu.' },
    { script: 'hira', kana: [{ c: 'は', r: 'ha' }, { c: 'ほ', r: 'ho' }, { c: 'ま', r: 'ma' }],
      hint: 'は (ha) — vertical bar, then a curl with one cross. ほ (ho) — same as は but with an EXTRA top bar. ま (ma) — vertical with TWO horizontal crosses, ends in a loop.' },
    { script: 'hira', kana: [{ c: 'ね', r: 'ne' }, { c: 'れ', r: 're' }, { c: 'わ', r: 'wa' }],
      hint: 'ね (ne) — ends in a CURLY loop (cat tail). れ (re) — ends in a tiny hook. わ (wa) — ends with NO loop or hook, just a flick.' },
    { script: 'hira', kana: [{ c: 'る', r: 'ru' }, { c: 'ろ', r: 'ro' }, { c: 'そ', r: 'so' }],
      hint: 'る (ru) — ends in a CLOSED loop. ろ (ro) — same shape, NO loop. そ (so) — has a sharp zigzag at the top before the curve.' },
    { script: 'hira', kana: [{ c: 'ぬ', r: 'nu' }, { c: 'め', r: 'me' }],
      hint: 'ぬ (nu) — ends in a curly LOOP (tangled noodles). め (me) — same start, NO loop at the end.' },
    { script: 'hira', kana: [{ c: 'ち', r: 'chi' }, { c: 'ら', r: 'ra' }],
      hint: 'ち (chi) — top cross is HORIZONTAL, body curls LEFT (like a backwards 5). ら (ra) — top is a small slant, body curls RIGHT.' },
    { script: 'hira', kana: [{ c: 'き', r: 'ki' }, { c: 'さ', r: 'sa' }, { c: 'ち', r: 'chi' }],
      hint: 'き (ki) — TWO horizontals + curl going LEFT. さ (sa) — ONE horizontal + curl going LEFT. ち (chi) — ONE horizontal + curl going RIGHT (mirror of さ).' },
    { script: 'kata', kana: [{ c: 'ク', r: 'ku' }, { c: 'ケ', r: 'ke' }, { c: 'タ', r: 'ta' }],
      hint: 'ク (ku) — just two strokes, no extras. ケ (ke) — adds a small slash on the LEFT. タ (ta) — adds a small slash INSIDE.' },
    { script: 'kata', kana: [{ c: 'フ', r: 'fu' }, { c: 'ワ', r: 'wa' }, { c: 'ラ', r: 'ra' }],
      hint: 'フ (fu) — a single bent stroke (like a 7). ワ (wa) — フ + a vertical drop on the right. ラ (ra) — フ + a short bar floating above.' },
    { script: 'kata', kana: [{ c: 'ナ', r: 'na' }, { c: 'メ', r: 'me' }, { c: 'ヌ', r: 'nu' }],
      hint: 'ナ (na) — clean cross "+". メ (me) — diagonal X. ヌ (nu) — like メ but the top stroke extends LEFT.' },
    { script: 'kata', kana: [{ c: 'チ', r: 'chi' }, { c: 'テ', r: 'te' }],
      hint: 'チ (chi) — top is a small slant, then a cross with a curl. テ (te) — top is a STRAIGHT bar, then a cross, then a vertical drop (no curl).' },
  ];

  return {
    sets: {
      hiraganaBasic, hiraganaDakuten,
      katakanaBasic, katakanaDakuten,
    },
    words, wordCategories, tricky,
    facts, quotes,
  };
})();
